In [ ]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

In [ ]:
file_path = "mushrooms.csv"
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "uciml/mushroom-classification",
  file_path
)

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
df_encoded = df.copy()

for col in df.columns:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df[col])

In [ ]:
df_encoded.head()

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
# Compute the correlation matrix
corr = df_encoded.corr()  # Pearson correlation

# Plot the correlation matrix
plt.figure(figsize=(12, 10))
plt.matshow(corr, fignum=1, cmap='coolwarm')  # Matshow inside figure
plt.colorbar()  # Show color scale
plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
plt.yticks(range(len(corr.columns)), corr.columns)
plt.title("Correlation Matrix of Mushroom Dataset", pad=30)
plt.show()

## As according to assignment, we are allow to choose subset of features. So, I am going to choose 4 features include target

In [36]:
new_df = df_encoded[['gill-size', 'odor', 'cap-surface', 'class']]
new_df.head()

   gill-size  odor  cap-surface  class
0          1     6            2      1
1          0     0            2      0
2          0     3            2      0
3          1     6            3      1
4          0     5            2      0

In [37]:
new_df.describe()

         gill-size         odor  cap-surface        class
count  8124.000000  8124.000000  8124.000000  8124.000000
mean      0.309207     4.144756     1.827671     0.482029
std       0.462195     2.103729     1.229873     0.499708
min       0.000000     0.000000     0.000000     0.000000
25%       0.000000     2.000000     0.000000     0.000000
50%       0.000000     5.000000     2.000000     0.000000
75%       1.000000     5.000000     3.000000     1.000000
max       1.000000     8.000000     3.000000     1.000000

In [38]:
new_df['class'].value_counts(normalize=True) * 100

class
0    51.797144
1    48.202856
Name: proportion, dtype: float64